services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # allow Jenkins to run docker exec
#    networks:
#      - ci_network

volumes:
  jenkins_home:
#  ansible:
#    build: ./ansible
#    container_name: ansible
#    tty: true
#    volumes:
#      - ./ansible:/ansible
#      - /var/run/docker.sock:/var/run/docker.sock  # allow Jenkins to run docker exec
#    ports:
#      - "2222:22"
#    networks:
#      - ci_network



#networks:
#  ci_network:
#    driver: bridge
