FROM cytopia/ansible:latest

# If your playbooks need extra tools (like python libraries or specific CLI tools), 
# install them here.
RUN apk add --no-cache bash

# Set working directory
WORKDIR /ansible