---
  - name: Install Docker (Debian/Ubuntu)
    apt:
      name: docker.io
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Ensure docker is running
    service:
      name: docker
      state: started
      enabled: yes

  - name: Ajouter l'utilisateur distant au groupe docker
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Stop and remove the old container
    docker_container:
      name: "{{ app_name }}"
      state: absent

  - name: Pull the latest image
    docker_image:
      name: "{{ image_name }}"
      source: pull

  - name: Run the new container
    docker_container:
      name: "{{ app_name }}"
      image: "{{ image_name }}"
      state: started
      restart_policy: always
      ports:
        - "80:8083"